name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # または対象のブランチ名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PATaaaa }}  # 個人アクセストークン
          external_repository: klcr/pdf-reviewer-app # パブリックリポジトリ
          publish_branch: gh-pages  # 公開用ブランチ
          publish_dir: ./build  # ビルド成果物のディレクトリ